export enum Cities {
    Adelaide = 'Adelaide',
    Brisbane = 'Brisbane',
    BrokenHill = 'Broken Hill',
    Geelong = 'Geelong',
    GoldCoast = 'Gold Coast',
    Hobart = 'Hobart',
    Latrobe = 'Latrobe',
    Launceston = 'Launceston',
    LucasHeights = 'Lucas Heights',
    Melbourne = 'Melbourne',
    Mildura = 'Mildura',
    MountThorley = 'Mount Thorley',
    Newcastle = 'Newcastle',
    OlympicDam = 'Olympic Dam',
    PortPirie = 'Port Pirie',
    RadiumHill = 'Radium Hill',
    Sydney = 'Sydney',
    Toongi = 'Toongi',
    ToongiCoal = 'Toongi (Coal Mine)',
    Toowoomba = 'Toowomba',
    WaggaWagga = 'Wagga Wagga',
    Wollongong = 'Wollongong',
    Wooltana = 'Wooltana',
}