export enum Cities {
    Aussig = 'Aussig',
    Bautzen = 'Bautzen',
    Brux = 'Brüx',
    Chemnitz = 'Chemnitz',
    Dresden = 'Dresden',
    Freiberg = 'Freiberg',
    Glashutte = 'Glashütte',
    Gorlitz = 'Görlitz',
    Grimma = 'Grimma',
    Joachimsthal = 'Joachimsthal',
    Karlsbad = 'Karlsbad',
    Leipzig = 'Leipzig',
    Marienberg = 'Marienberg',
    Plauen = 'Plauen',
    Praha = 'Praha',
    Presnitz = 'Preßnitz',
    Riesa = 'Riesa',
    Zittau = 'Zittau',
    Zwickau = 'Zwickau',
}